apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-orchestrator
  template:
    metadata:
      labels:
        app: health-orchestrator
    spec:
      containers:
        - name: health-orchestrator
          image: health-orchestrator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
