apiVersion: v1
kind: Service
metadata:
  name: health-orchestrator-service
spec:
  type: NodePort
  selector:
    app: health-orchestrator
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30036
