apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-orchestrator
  template:
    metadata:
      labels:
        app: health-orchestrator
    spec:
      containers:
        - name: health-orchestrator
                  image: health-orchestrator:latest     # ✅ Local image name
          imagePullPolicy: Never                # ✅ Don’t pull from Docker Hub
            
          ports:
            - containerPort: 80
