apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-orchestrator
  labels:
    app: health-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-orchestrator
  template:
    metadata:
      labels:
        app: health-orchestrator
    spec:
      containers:
        - name: orchestrator
          image: health-orchestrator:latest
          ports:
            - containerPort: 5000  # API
            - containerPort: 8000  # Metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: FLASK_ENV
              value: production
