apiVersion: v1
kind: Service
metadata:
  name: health-orchestrator
spec:
  type: NodePort
  selector:
    app: health-orchestrator
  ports:
    - name: api
      port: 5000
      targetPort: 5000
      nodePort: 30001
    - name: metrics
      port: 8000
      targetPort: 8000
      nodePort: 30002
